# Setup
title:               Shuaimin's Blog
tagline:             'A Jekyll theme'
description:         'A blog for personal learning'
url:                
baseurl:             'shuaimin_blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Shuaimin Wu
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
